# Generated by Django 4.0.4 on 2022-07-12 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_post_name_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
    ]
