# Generated by Django 4.0.4 on 2022-07-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='p_title',
        ),
    ]
